spring:
  config:
    import: "classpath:properties/application-dev.yml"
    activate:
      on-profile: dev

---

spring:
  config:
    import: "classpath:properties/application-dev.yml"
    activate:
      on-profile: prod
