spring:
  profiles:
    active: dev
  config:
    import: "classpath:properties/application-dev.yml"

---

spring:
  profiles:
    active: prod
  config:
    import: "classpath:properties/application-prod.yml"
