= GoalRoom API
:toc-title: GoalRoom API Docs
:doctype: book
:icons: font
:source-highlighter: highlightjs
:toc: left
:toclevels: 2
:sectlinks:
ifndef::snippets[]
:snippets: ../../../build/generated-snippets
endif::[]
ifndef::page[]
:page: src/docs/asciidoc
endif::[]

[[골룸생성-API]]
== *1. 골룸 생성*

=== *1-1* 성공

operation::goal-room-create-api-test/정상적으로_골룸을_생성한다[snippets='http-request,http-response,request-fields']

=== *1-2* 실패 - 골룸 생성 시 요청에 빈값이 있을 경우

operation::goal-room-create-api-test/골룸_생성_시_요청에_빈값이_있을_경우[snippets='http-request,http-response']

=== *1-3* 실패 - 골룸 생성 시 로드맵에 존재하지 않는 노드일 경우

operation::goal-room-create-api-test/골룸_생성_시_로드맵에_존재하지_않는_노드일_경우[snippets='http-request,http-response']

=== *1-4* 실패 - 골룸 생성 시 로드맵의 노드 크기와 요청의 노드 크기가 일치하지 않을 경우

operation::goal-room-create-api-test/골룸_생성_시_로드맵의_노드_크기와_요청의_노드_크기가_일치하지_않을_경우[snippets='http-request,http-response']

=== *1-5* 실패 - 골룸 생성 시 로드맵이 존재하지 않을 경우

operation::goal-room-create-api-test/골룸_생성_시_로드맵이_존재하지_않을_경우[snippets='http-request,http-response']

=== *1-6* 실패 - 골룸 생성 시 존재하지 않는 회원일 경우

operation::goal-room-create-api-test/골룸_생성_시_존재하지_않는_회원일_경우[snippets='http-request,http-response']
