= GoalRoom API
:toc-title: GoalRoom API Docs
:doctype: book
:icons: font
:source-highlighter: highlightjs
:toc: left
:toc-title: GoalRoom API Docs
:toclevels: 2
:sectlinks:
ifndef::snippets[]
:snippets: ../../../build/generated-snippets
endif::[]
ifndef::page[]
:page: src/docs/asciidoc
endif::[]

[[골룸생성-API]]
== *1. 골룸 생성*

=== *1-1* 성공

operation::goal-room-create-api-test/정상적으로_골룸을_생성한다[snippets='http-request,http-response,request-fields,response-headers']

=== *1-2* 실패 - 골룸 생성 시 요청에 빈값이 있을 경우

operation::goal-room-create-api-test/골룸_생성_시_요청에_빈값이_있을_경우[snippets='http-request,http-response']

=== *1-3* 실패 - 골룸 생성 시 로드맵에 존재하지 않는 노드일 경우

operation::goal-room-create-api-test/골룸_생성_시_로드맵에_존재하지_않는_노드일_경우[snippets='http-request,http-response']

=== *1-4* 실패 - 골룸 생성 시 로드맵의 노드 크기와 요청의 노드 크기가 일치하지 않을 경우

operation::goal-room-create-api-test/골룸_생성_시_로드맵의_노드_크기와_요청의_노드_크기가_일치하지_않을_경우[snippets='http-request,http-response']

=== *1-5* 실패 - 골룸 생성 시 로드맵이 존재하지 않을 경우

operation::goal-room-create-api-test/골룸_생성_시_로드맵이_존재하지_않을_경우[snippets='http-request,http-response']

=== *1-6* 실패 - 골룸 생성 시 존재하지 않는 회원일 경우

operation::goal-room-create-api-test/골룸_생성_시_존재하지_않는_회원일_경우[snippets='http-request,http-response']

=== *1-7* 실패 - 골룸 생성 시 골룸 투두의 시작 날짜가 오늘보다 전일 경우

operation::goal-room-create-api-test/골룸_생성_시_골룸_투두의_시작_날짜가_오늘보다_전일_경우[snippets='http-request,http-response']

=== *1-8* 실패 - 골룸 생성 시 골룸 투두의 시작 날짜보다 종료 날짜가 빠른 경우

operation::goal-room-create-api-test/골룸_생성_시_골룸_투두의_시작_날짜보다_종료_날짜가_빠른_경우[snippets='http-request,http-response']

=== *1-9* 실패 - 골룸 생성 시 골룸 노드의 시작 날짜가 오늘보다 전일 경우

operation::goal-room-create-api-test/골룸_생성_시_골룸_노드의_시작_날짜가_오늘보다_전일_경우[snippets='http-request,http-response']

=== *1-10* 실패 - 골룸 생성 시 골룸 노드의 시작 날짜보다 종료 날짜가 빠른 경우

operation::goal-room-create-api-test/골룸_생성_시_골룸_노드의_시작_날짜보다_종료_날짜가_빠른_경우[snippets='http-request,http-response']

=== *1-11* 실패 - 골룸 생성 시 골룸 노드의 인증 횟수가 0보다 작을 경우

operation::goal-room-create-api-test/골룸_생성_시_골룸_노드의_인증_횟수가_0보다_작을_경우[snippets='http-request,http-response']

=== *1-12* 실패 - 골룸 생성 시 골룸 노드의 인증 횟수가 기간보다 클 경우

operation::goal-room-create-api-test/골룸_생성_시_골룸_노드의_인증_횟수가_기간보다_클_경우[snippets='http-request,http-response']

[[골룸단일조회-API]]
== *2. 골룸 단일 조회 API (비로그인)*

=== *2-1* 성공

operation::goal-room-read-api-test/골룸_아이디로_골룸을_조회한다[snippets='http-request,http-response,response-fields']

=== *2-2* 실패

operation::goal-room-read-api-test/골룸_아이디로_골룸_조회시_아이디가_유효하지_않으면_예외가_발생한다[snippets='http-request,http-response,response-fields']

== *3. 골룸 단일 조회 API (로그인)*

=== *3-1* 성공

operation::goal-room-read-api-test/골룸_아이디와_사용자_아이디로_골룸을_조회한다[snippets='http-request,request-headers,http-response,response-fields']

=== *3-2* 실패

operation::goal-room-read-api-test/골룸_아이디와_사용자_아이디로_골룸_조회시_골룸_아이디가_유효하지_않으면_예외_발생[snippets='http-request,request-headers,http-response,response-fields']

[[골룸참가-API]]
== *4. 골룸 참가 API*

=== *4-1* 성공

operation::goal-room-create-api-test/골룸_참가_요청을_성공한다[snippets='http-request,http-response,request-headers,path-parameters']

=== *4-2* 실패 - 골룸의 아이디가 유효하지 않음

operation::goal-room-create-api-test/존재하지_않는_골룸에_대한_참가_요청은_실패한다[snippets='http-request,http-response,request-headers,path-parameters,response-fields']

=== *4-3* 실패 - 이미 해당 골룸에 참여함

operation::goal-room-create-api-test/이미_참여한_골룸에_대한_참가_요청은_실패한다[snippets='http-request,http-response,request-headers,path-parameters,response-fields']

=== *4-4* 실패 - 골룸의 제한 인원이 가득 참

operation::goal-room-create-api-test/제한_인원이_가득_찬_골룸에_대한_참가_요청은_실패한다[snippets='http-request,http-response,request-headers,path-parameters,response-fields']

[[골룸참가자조회-API]]
== *5. 골룸 참가자 조회 API*

=== *5-1* 성공

operation::goal-room-read-api-test/정상적으로_골룸_멤버를_조회한다[snippets='http-request,http-response,path-parameters']

=== *5-2* 실패 - 골룸 멤버 조회 시 존재하지 않는 골룸일 경우

operation::goal-room-read-api-test/골룸_멤버_조회_시_존재하지_않는_골룸일_경우[snippets='http-request,http-response,request-headers,path-parameters,response-fields']

[[골룸투두추가-API]]
== *6. 골룸 투두 추가 API*

=== *6-1* 성공

operation::goal-room-create-api-test/정상적으로_골룸에_투두리스트를_추가한다[snippets='http-request,http-response,request-fields,request-headers,path-parameters,response-headers']

=== *6-2* 실패 - 골룸 투두 추가시 존재하지 않는 회원일 경우

operation::goal-room-create-api-test/골룸_투두_추가시_존재하지_않는_회원일_경우[snippets='http-request,http-response,request-headers,path-parameters,response-fields']

=== *6-3* 실패 - 골룸 투두 추가시 존재하지 않는 골룸일 경우

operation::goal-room-create-api-test/골룸_투두_추가시_존재하지_않는_골룸일_경우[snippets='http-request,http-response,request-headers,path-parameters,response-fields']

=== *6-4* 실패 - 골룸 투두 추가시 이미 종료된 골룸일 경우

operation::goal-room-create-api-test/골룸_투두_추가시_이미_종료된_골룸일_경우[snippets='http-request,http-response,request-headers,path-parameters,response-fields']

=== *6-5* 실패 - 골룸 투두 추가시 리더가 아닌 경우

operation::goal-room-create-api-test/골룸_투두_추가시_리더가_아닌_경우[snippets='http-request,http-response,request-headers,path-parameters,response-fields']

=== *6-6* 실패 - 골룸 투두 추가시 컨텐츠가 250글자가 넘을 경우

operation::goal-room-create-api-test/골룸_투두_추가시_컨텐츠가_250글자가_넘을_경우[snippets='http-request,http-response,request-headers,path-parameters,response-fields']

[[골룸인증피드전체조회-API]]
== *7. 골룸 인증 피드 전체 조회 API*

=== *7-1* 성공

operation::goal-room-read-api-test/골룸의_인증피드를_전체_조회한다[snippets='http-request,path-parameters,request-headers,http-response,response-fields']

=== *7-2* 실패 - 골룸 인증 피드 전체 조회 시 존재하지 않는 골룸인 경우

operation::goal-room-read-api-test/골룸_인증피드_전체_조회_시_존재하지_않는_골룸일_경우_예외가_발생한다[snippets='http-request,http-response,response-fields']

=== *7-3* 실패 - 골룸 인증 피드 전체 조회 시 해당 골룸에 참여하지 않은 사용자인 경우

operation::goal-room-read-api-test/골룸_인증피드_전체_조회_시_골룸에_참여하지_않은_사용자일_경우_예외가_발생한다[snippets='http-request,http-response,response-fields']
