= Member API
:toc-title: Member API Docs
:doctype: book
:icons: font
:source-highlighter: highlightjs
:toc: left
:toclevels: 2
:sectlinks:
ifndef::snippets[]
:snippets: ../../../build/generated-snippets
endif::[]
ifndef::page[]
:page: src/docs/asciidoc
endif::[]

[[회원가입-API]]
== *1. 회원 가입*

=== *1-1* 성공

operation::member-controller-test/정상적으로_회원가입에_성공한다[snippets='http-request,http-response']

=== *1-2* 실패 - 아이디가 형식에 맞지 않을 때

operation::member-controller-test/회원가입_시_아이디가_형식에_맞지않을때[snippets='http-request,http-response']

=== *1-3* 실패 - 비밀번호 형식에 맞지 않을 때

operation::member-controller-test/회원가입_시_비밀번호가_형식에_맞지않을때[snippets='http-request,http-response']

=== *1-4* 실패 - 닉네임이 형식에 맞지 않을 때

operation::member-controller-test/회원가입_시_닉네임이_형식에_맞지않을때[snippets='http-request,http-response']

=== *1-5* 실패 - 전화번호 형식에 맞지 않을 때

operation::member-controller-test/회원가입_시_전화번호_형식에_맞지않을때[snippets='http-request,http-response']

=== *1-6* 실패 - 중복된 아이디일 때

operation::member-controller-test/회원가입_시_중복된_닉네임일_때[snippets='http-request,http-response']

=== *1-7* 실패 - 중복된 닉네임일 때

operation::member-controller-test/회원가입_시_중복된_아이디일_때[snippets='http-request,http-response']
