= Roadmap API
:doctype: book
:icons: font
:source-highlighter: highlightjs
:toc: left
:toc-title: Roadmap API Docs
:toclevels: 2
:sectlinks:
ifndef::snippets[]
:snippets: ../../../build/generated-snippets
endif::[]
ifndef::page[]
:page: src/docs/asciidoc
endif::[]


[[로드맵생성-API]]
== *1. 로드맵 생성 API*

=== *1-1* 성공
operation::roadmap-create-api-test/정상적으로_로드맵을_생성한다[snippets='http-request,request-headers,request-fields,http-response,response-headers']

=== *1-2* 실패 - 카테고리 아이디가 유효하지 않음
operation::roadmap-create-api-test/로드맵_생성시_유효하지_않은_카테고리_아이디를_입력하면_예외가_발생한다[snippets='http-request,http-response']

=== *1-3* 실패 - 카테고리를 입력하지 않음
operation::roadmap-create-api-test/로드맵_생성시_카테고리_아이디를_입력하지_않으면_예외가_발생한다[snippets='http-request,http-response']

=== *1-4* 실패 - 로드맵 제목의 길이가 40보다 큼
operation::roadmap-create-api-test/로드맵_생성시_로드맵_제목의_길이가_40보다_크면_예외가_발생한다[snippets='http-request,http-response']

=== *1-5* 실패 - 로드맵 제목을 입력하지 않음
operation::roadmap-create-api-test/로드맵_생성시_로드맵_제목을_입력하지_않으면_예외가_발생한다[snippets='http-request,http-response']

=== *1-6* 실패 - 로드맵 소개글의 길이가 150보다 큼
operation::roadmap-create-api-test/로드맵_생성시_로드맵_소개글의_길이가_150보다_크면_예외가_발생한다[snippets='http-request,http-response']

=== *1-7* 실패 - 로드맵 소개글을 입력하지 않음
operation::roadmap-create-api-test/로드맵_생성시_로드맵_소개글을_입력하지_않으면_예외가_발생한다[snippets='http-request,http-response']

=== *1-8* 실패 - 로드맵 본문의 길이가 2000보다 큼
operation::roadmap-create-api-test/로드맵_생성시_로드맵_본문의_길이가_2000보다_크면_예외가_발생한다[snippets='http-request,http-response']

=== *1-9* 실패 - 로드맵 난이도를 입력하지 않음
operation::roadmap-create-api-test/로드맵_생성시_로드맵_난이도를_입력하지_않으면_예외가_발생한다[snippets='http-request,http-response']

=== *1-10* 실패 - 로드맵 추천 소요 기간이 0보다 작거나 1000보다 큼
operation::roadmap-create-api-test/로드맵_생성시_로드맵_추천_소요기간이_0보다_작거나_1000보다_크면_예외가_발생한다[snippets='http-request,http-response']

=== *1-11* 실패 - 로드맵 추천 소요 기간을 입력하지 않음
operation::roadmap-create-api-test/로드맵_생성시_로드맵_추천_소요기간을_입력하지_않으면_예외가_발생한다[snippets='http-request,http-response']

=== *1-12* 실패 - 로드맵 노드의 제목의 길이가 40보다 큼
operation::roadmap-create-api-test/로드맵_생성시_로드맵_노드의_제목의_길이가_40보다_크면_예외가_발생한다[snippets='http-request,http-response']

=== *1-13* 실패 - 로드맵 노드의 제목을 입력하지 않음
operation::roadmap-create-api-test/로드맵_생성시_로드맵_노드의_제목을_입력하지_않으면_예외가_발생한다[snippets='http-request,http-response']

=== *1-14* 실패 - 로드맵 노드의 설명의 길이가 2000보다 큼
operation::roadmap-create-api-test/로드맵_생성시_로드맵_노드의_설명의_길이가_2000보다_크면_예외가_발생한다[snippets='http-request,http-response']

=== *1-15* 실패 - 로드맵 노드의 설명을 입력하지 않음
operation::roadmap-create-api-test/로드맵_생성시_로드맵_노드의_설명을_입력하지_않으면_예외가_발생한다[snippets='http-request,http-response']

=== *1-16* 실패 - 로드맵 태그의 이름에 중복이 있음
operation::roadmap-create-api-test/로드맵_생성시_중복된_태그_이름이_있으면_예외가_발생한다[snippets='http-request,http-response']

=== *1-17* 실패 - 로드맵 태그의 개수가 5개 초과임
operation::roadmap-create-api-test/로드맵_생성시_태그_개수가_5개_초과면_예외가_발생한다[snippets='http-request,http-response']

=== *1-18* 실패 - 로드맵 태그의 이름이 1자 미만 10자 초과임
operation::roadmap-create-api-test/로드맵_생성시_태그_이름이_1미만_10초과면_예외가_발생한다[snippets='http-request,http-response']

=== *1-19* 실패 - 로드맵 생성 시 회원이 존재하지 않음
operation::roadmap-create-api-test/로드맵_생성시_존재하지_않은_회원이면_예외가_발생한다[snippets='http-request,http-response']


[[로드맵목록조회-API]]
== *2. 로드맵 목록 조회 API*

=== *2-1* 성공
operation::roadmap-read-api-test/로드맵_목록을_조건에_따라_조회한다[snippets='http-request,query-parameters,http-response,response-fields']

=== *2-2* 실패 - 카테고리 아이디가 유효하지 않음
operation::roadmap-read-api-test/로드맵_목록_조회시_유효하지_않은_카테고리_아이디를_보내면_예외가_발생한다[snippets='http-request,http-response']

=== *2-3* 실패 - 사이즈 값을 전송하지 않음
operation::roadmap-read-api-test/로드맵_목록_조회시_사이즈_값을_전송하지_않으면_예외가_발생한다[snippets='http-request,http-response']

[[로드맵카테고리목록조회-API]]
== *3. 로드맵 카테고리 목록 조회 API*

=== *3-1* 성공
operation::roadmap-read-api-test/로드맵_카테고리_목록을_조회한다[snippets='http-request,http-response,response-fields']

[[로드맵단일조회-API]]
== *4. 로드맵 단일 조회 API*

=== *4-1* 성공
operation::roadmap-read-api-test/단일_로드맵_정보를_조회한다[snippets='http-request,path-parameters,http-response,response-fields']

=== *4-2* 실패 - 로드맵 아이디가 유효하지 않음
operation::roadmap-read-api-test/존재하지_않는_로드맵_아이디로_요청_시_예외를_반환한다[snippets='http-request,http-response']

[[로드맵검색-API]]
== *5. 로드맵 검색 + 필터링 API*

=== *5-1* 성공
operation::roadmap-read-api-test/로드맵을_조건별로_검색한다[snippets='http-request,query-parameters,http-response,response-fields']

=== *5-2* 실패
operation::roadmap-read-api-test/로드맵_검색시_사이즈_값을_전송하지_않으면_예외가_발생한다[snippets='http-request,http-response']

[[로드맵리뷰생성-API]]
== *6. 로드맵 리뷰 생성 API*

=== *6-1* 성공
operation::roadmap-create-api-test/로드맵의_리뷰를_생성한다[snippets='http-request,path-parameters,request-headers,request-fields,http-response']

=== *6-2* 실패 - 유효하지 않은 로드맵 아이디인 경우
operation::roadmap-create-api-test/로드맵_리뷰_생성시_존재하지_않은_로드맵이면_예외가_발생한다[snippets='http-request,http-response']

=== *6-3* 실패 - 별점이 null인 경우
operation::roadmap-create-api-test/로드맵_리뷰_생성시_별점이_null이라면_예외가_발생한다[snippets='http-request,http-response']

=== *6-4* 실패 - 리뷰 내용이 1000자가 넘는 경우
operation::roadmap-create-api-test/로드맵_리뷰_생성시_내용이_1000자가_넘으면_예외가_발생한다[snippets='http-request,http-response']

=== *6-5* 실패 - 리뷰 별점이 0~5 사이의 0.5씩 증가하는 값이 아닌 경우
operation::roadmap-create-api-test/로드맵_리뷰_생성시_별점이_잘못된_값이면_예외가_발생한다[snippets='http-request,http-response']

=== *6-6* 실패 - 해당 로드맵의 생성자가 리뷰를 달려고 하는 경우
operation::roadmap-create-api-test/로드맵_리뷰_생성시_로드맵_생성자가_리뷰를_달려고_하면_예외가_발생한다[snippets='http-request,http-response']

=== *6-7* 실패 - 로드맵을 완료한 골룸이 없는 경우
operation::roadmap-create-api-test/로드맵_리뷰_생성시_완료한_골룸이_없으면_예외가_발생한다[snippets='http-request,http-response']

=== *6-8* 실패 - 해당 로드맵에 이미 리뷰를 단 적이 있는 경우
operation::roadmap-create-api-test/로드맵_리뷰_생성시_이미_리뷰를_단적이_있으면_예외가_발생한다[snippets='http-request,http-response']
