name: client test CI

on:
  pull_request:
    branches: [ develop-client ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x]

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
      - run: |
          cd client
          npm ci
          npm run build --if-present
          npm run test:coverage

      - name: Display Coverage Report
        run: cat coverage.txt
